//! Compile the vendored OpenAPI spec into a static IR data table.
//!
//! This build script parses `spec/spec3.json`, keeps only the `documents.*`
//! operations (Story 1.1 scope), and code-generates a `static OPS` table of
//! `engine::ir::OpSpec` values into `$OUT_DIR/ir_table.rs`. It produces a
//! data table only - never per-endpoint functions.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;

/// Prefix selecting the operation subset compiled in this milestone.
const OP_PATH_PREFIX: &str = "/documents.";
/// Must match `engine::ir::IR_SCHEMA_VERSION`; asserted in generated code.
const IR_SCHEMA_VERSION: u32 = 1;

struct Op {
    name: String,
    path: String,
    params: Vec<Param>,
}

struct Param {
    name: String,
    ty: &'static str,
    required: bool,
}

fn main() {
    println!("cargo:rerun-if-changed=spec/spec3.json");

    let manifest_dir = env_var("CARGO_MANIFEST_DIR");
    let spec_path = Path::new(&manifest_dir).join("spec/spec3.json");
    let spec = load_spec(&spec_path);
    let ops = extract_ops(&spec);
    if ops.is_empty() {
        panic!(
            "no {OP_PATH_PREFIX}* operations found in {}",
            spec_path.display()
        );
    }

    let out_path = PathBuf::from(env_var("OUT_DIR")).join("ir_table.rs");
    if let Err(error) = fs::write(&out_path, render_table(&ops)) {
        panic!("failed to write {}: {error}", out_path.display());
    }
}

fn env_var(name: &str) -> String {
    match env::var(name) {
        Ok(value) => value,
        Err(error) => panic!("missing env var {name}: {error}"),
    }
}

fn load_spec(path: &Path) -> Value {
    let raw = match fs::read_to_string(path) {
        Ok(raw) => raw,
        Err(error) => panic!("failed to read vendored spec {}: {error}", path.display()),
    };
    match serde_json::from_str(&raw) {
        Ok(spec) => spec,
        Err(error) => panic!(
            "vendored spec {} is not valid JSON: {error}",
            path.display()
        ),
    }
}

/// Collect every POST operation under the configured path prefix.
fn extract_ops(spec: &Value) -> Vec<Op> {
    let Some(paths) = spec.get("paths").and_then(Value::as_object) else {
        panic!("spec has no object at `paths`");
    };
    let mut ops: Vec<Op> = paths
        .iter()
        .filter(|(path, _)| path.starts_with(OP_PATH_PREFIX))
        .filter_map(|(path, item)| {
            item.get("post").map(|post| Op {
                name: path.trim_start_matches('/').to_string(),
                path: path.clone(),
                params: extract_params(post),
            })
        })
        .collect();
    ops.sort_by(|a, b| a.name.cmp(&b.name));
    ops
}

/// Extract scalar request-body parameters from one POST operation.
///
/// Only top-level scalar properties are typed; everything else (objects,
/// arrays, unions, $ref) is marked `Json`. Non-JSON bodies yield no params.
fn extract_params(post: &Value) -> Vec<Param> {
    let schema = post
        .pointer("/requestBody/content/application~1json/schema")
        .unwrap_or(&Value::Null);
    let required: Vec<&str> = schema
        .get("required")
        .and_then(Value::as_array)
        .map(|list| list.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default();
    let Some(properties) = schema.get("properties").and_then(Value::as_object) else {
        return Vec::new();
    };
    properties
        .iter()
        .map(|(name, prop)| Param {
            name: name.clone(),
            ty: param_type(prop),
            required: required.contains(&name.as_str()),
        })
        .collect()
}

fn param_type(prop: &Value) -> &'static str {
    match prop.get("type").and_then(Value::as_str) {
        Some("string") => "String",
        Some("integer") => "Integer",
        Some("boolean") => "Boolean",
        Some("number") => "Number",
        _ => "Json",
    }
}

/// Render the static table as Rust source referencing `engine::ir` types.
fn render_table(ops: &[Op]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by build.rs from spec/spec3.json - do not edit."
    );
    let _ = writeln!(
        out,
        "const _: () = assert!(engine::ir::IR_SCHEMA_VERSION == {IR_SCHEMA_VERSION});"
    );
    let _ = writeln!(out, "/// Static IR table of all compiled operations.");
    let _ = writeln!(out, "pub static OPS: &[engine::ir::OpSpec] = &[");
    for op in ops {
        let _ = writeln!(out, "    engine::ir::OpSpec {{");
        let _ = writeln!(
            out,
            "        name: ::std::borrow::Cow::Borrowed({:?}),",
            op.name
        );
        let _ = writeln!(
            out,
            "        path: ::std::borrow::Cow::Borrowed({:?}),",
            op.path
        );
        let _ = writeln!(out, "        params: ::std::borrow::Cow::Borrowed(&[");
        for param in &op.params {
            let _ = writeln!(
                out,
                "            engine::ir::ParamSpec {{ name: ::std::borrow::Cow::Borrowed({:?}), \
                 ty: engine::ir::ParamType::{}, required: {} }},",
                param.name, param.ty, param.required
            );
        }
        let _ = writeln!(out, "        ]),");
        let _ = writeln!(out, "    }},");
    }
    let _ = writeln!(out, "];");
    out
}
