//! Compile the vendored OpenAPI spec into a static IR data table.
//!
//! The parsing itself lives in the `spec-compile` crate, which `otl spec
//! sync` also uses at run time - so the built-in table and a synced one
//! are produced by exactly one implementation. This script only renders
//! the compiled table as `static OPS` into `$OUT_DIR/ir_table.rs`. It
//! produces a data table only, never per-endpoint functions.

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use spec_compile::{
    BodyKind, CompiledField, CompiledOp, CompiledParam, FieldContainer, ScalarKind,
};

/// Outline URL convention: every RPC path lives under this prefix. This is
/// an Outline-specific rule, so it is applied here (the otl layer), never
/// in the engine or the compiler - the engine joins `base_url + op.path`
/// verbatim.
const API_PATH_PREFIX: &str = "/api";
/// Outline envelope convention: the payload of a success response lives
/// under `data`. Service-specific, so it is applied here (the otl layer)
/// and never in the engine or the compiler.
const ENVELOPE_DATA_PROPERTY: &str = "data";
/// Must match `engine::ir::IR_SCHEMA_VERSION`; asserted in generated code.
const IR_SCHEMA_VERSION: u32 = 7;

fn main() {
    println!("cargo:rerun-if-changed=spec/spec3.json");

    let manifest_dir = env_var("CARGO_MANIFEST_DIR");
    let spec_path = Path::new(&manifest_dir).join("spec/spec3.json");
    let raw = match fs::read_to_string(&spec_path) {
        Ok(raw) => raw,
        Err(error) => panic!(
            "failed to read vendored spec {}: {error}",
            spec_path.display()
        ),
    };
    let options = spec_compile::CompileOptions::with_prefix(API_PATH_PREFIX)
        .with_envelope(ENVELOPE_DATA_PROPERTY);
    let compiled = match spec_compile::compile_json(&raw, &options) {
        Ok(compiled) => compiled,
        Err(error) => panic!("vendored spec {} is unusable: {error}", spec_path.display()),
    };

    let out_path = PathBuf::from(env_var("OUT_DIR")).join("ir_table.rs");
    if let Err(error) = fs::write(&out_path, render_table(&compiled.ops)) {
        panic!("failed to write {}: {error}", out_path.display());
    }
}

fn env_var(name: &str) -> String {
    match env::var(name) {
        Ok(value) => value,
        Err(error) => panic!("missing env var {name}: {error}"),
    }
}

/// Render the static table as Rust source referencing `engine::ir` types.
fn render_table(ops: &[CompiledOp]) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// @generated by build.rs from spec/spec3.json - do not edit."
    );
    let _ = writeln!(
        out,
        "const _: () = assert!(engine::ir::IR_SCHEMA_VERSION == {IR_SCHEMA_VERSION});"
    );
    let _ = writeln!(out, "/// Static IR table of all compiled operations.");
    let _ = writeln!(out, "pub static OPS: &[engine::ir::OpSpec] = &[");
    for op in ops {
        render_op(&mut out, op);
    }
    let _ = writeln!(out, "];");
    out
}

fn render_op(out: &mut String, op: &CompiledOp) {
    let _ = writeln!(out, "    engine::ir::OpSpec {{");
    for (field, value) in [
        ("name", &op.name),
        ("path", &op.path),
        ("summary", &op.summary),
        ("content_type", &op.content_type),
    ] {
        let _ = writeln!(
            out,
            "        {field}: ::std::borrow::Cow::Borrowed({value:?}),"
        );
    }
    let _ = writeln!(
        out,
        "        body_mode: engine::ir::BodyMode::{},",
        body_mode_variant(op.body_mode)
    );
    let _ = writeln!(out, "        params: ::std::borrow::Cow::Borrowed(&[");
    for param in &op.params {
        render_param(out, param);
    }
    let _ = writeln!(out, "        ]),");
    let _ = writeln!(
        out,
        "        response_fields: ::std::borrow::Cow::Borrowed(&["
    );
    for field in &op.response_fields {
        render_field(out, field);
    }
    let _ = writeln!(out, "        ]),");
    let _ = writeln!(out, "    }},");
}

fn render_field(out: &mut String, field: &CompiledField) {
    let _ = writeln!(out, "            engine::ir::FieldSpec {{");
    let _ = writeln!(
        out,
        "                name: ::std::borrow::Cow::Borrowed({:?}),",
        field.name
    );
    let _ = writeln!(
        out,
        "                ty: engine::ir::ParamType::{},",
        param_type_variant(field.ty)
    );
    let _ = writeln!(
        out,
        "                format: ::std::borrow::Cow::Borrowed({:?}),",
        field.format
    );
    let _ = writeln!(
        out,
        "                nullable: {}, read_only: {},",
        field.nullable, field.read_only
    );
    let _ = writeln!(out, "                depth: {},", field.depth);
    let _ = writeln!(
        out,
        "                container: engine::ir::FieldContainer::{},",
        field_container_variant(field.container)
    );
    let _ = writeln!(out, "            }},");
}

fn field_container_variant(container: FieldContainer) -> &'static str {
    match container {
        FieldContainer::None => "None",
        FieldContainer::Object => "Object",
        FieldContainer::Array => "Array",
        FieldContainer::Union => "Union",
    }
}

fn render_param(out: &mut String, param: &CompiledParam) {
    let enum_values: String = param
        .enum_values
        .iter()
        .map(|value| format!("::std::borrow::Cow::Borrowed({value:?}), "))
        .collect();
    let _ = writeln!(out, "            engine::ir::ParamSpec {{");
    let _ = writeln!(
        out,
        "                name: ::std::borrow::Cow::Borrowed({:?}),",
        param.name
    );
    let _ = writeln!(
        out,
        "                ty: engine::ir::ParamType::{}, required: {},",
        param_type_variant(param.ty),
        param.required
    );
    let _ = writeln!(
        out,
        "                nullable: {}, enum_values: ::std::borrow::Cow::Borrowed(&[{enum_values}]),",
        param.nullable
    );
    let _ = writeln!(
        out,
        "                format: ::std::borrow::Cow::Borrowed({:?}),",
        param.format
    );
    let _ = writeln!(
        out,
        "                minimum: {}, maximum: {},",
        render_bound(param.minimum),
        render_bound(param.maximum)
    );
    let _ = writeln!(
        out,
        "                description: ::std::borrow::Cow::Borrowed({:?}),",
        param.description
    );
    let _ = writeln!(out, "            }},");
}

/// Name of the `engine::ir::BodyMode` variant for a compiled body kind.
///
/// Exhaustive on purpose: a new variant in the compiler must be mapped
/// here (and in the runtime conversion) rather than defaulted.
fn body_mode_variant(kind: BodyKind) -> &'static str {
    match kind {
        BodyKind::KeyValue => "KeyValue",
        BodyKind::RawJsonOnly => "RawJsonOnly",
        BodyKind::Unsupported => "Unsupported",
    }
}

/// Name of the `engine::ir::ParamType` variant for a compiled scalar kind.
fn param_type_variant(kind: ScalarKind) -> &'static str {
    match kind {
        ScalarKind::String => "String",
        ScalarKind::Integer => "Integer",
        ScalarKind::Boolean => "Boolean",
        ScalarKind::Number => "Number",
        ScalarKind::Json => "Json",
    }
}

/// Render an optional numeric bound as a Rust literal.
fn render_bound(bound: Option<f64>) -> String {
    match bound {
        Some(value) if value.is_finite() => format!("::core::option::Option::Some({value:?}_f64)"),
        _ => "::core::option::Option::None".to_string(),
    }
}
