#!/usr/bin/env bash
# Verify the cargo-dist installer scripts that the generated release workflow
# pipes into a shell, against checksums pinned in this repository.
#
# Why this exists: `.github/workflows/release.yml` is generated by cargo-dist,
# and it installs dist by piping a remote script into a shell -
#
#     curl --proto '=https' --tlsv1.2 -LsSf .../cargo-dist-installer.sh | sh
#
# which executes remote content with no integrity check. dist offers no
# configuration to pin or verify that script (upstream issue
# https://github.com/axodotdev/cargo-dist/issues/2420), and the workflow is
# byte-compared by `dist generate --check`, so it cannot be hand-edited
# either. What is left is to verify the same bytes out-of-band and make the
# release fail when they change.
#
# This is a genuine control, not a fig leaf, because the installer script is
# self-contained: it embeds the SHA-256 of every dist binary tarball it may
# download (verified 2026-08: the hashes inside cargo-dist-installer.sh for
# v0.32.0 match upstream's published sha256.sum byte for byte). Pinning the
# script's own hash therefore also pins the binary it installs.
#
# What it does NOT do: it cannot stop the installer from running. This check
# lives in the release-guards job, and the generated workflow reaches dist by
# two routes, neither of which consults this pin (verified against the
# generated release.yml, job by job):
#
#   downloads and pipes the installer itself
#     plan                    `curl ... cargo-dist-installer.sh | sh`
#     build-local-artifacts   `${{ matrix.install_dist.run }}` per leg,
#                             which is `irm ... .ps1 | iex` on Windows
#
#   reuses the binary `plan` installed, via the cargo-dist-cache artifact
#     build-global-artifacts  download-artifact + chmod
#     host                    download-artifact + chmod
#
#   installs dist at all: no
#     publish-homebrew-formula, announce, and the two custom jobs
#
# So a swapped installer may already have executed in `plan` or a build leg
# by the time a mismatch is reported, and it propagates from `plan` to
# build-global and host through the cache without being re-verified. That is
# a TOCTOU gap, and it is upstream's to close (#2420 again): the workflow is
# byte-compared, so a verification step cannot be inserted into those jobs.
#
# What it does guarantee is that a mismatch stops the *release*: release-guards
# is registered as a `local-artifacts-jobs` job, which `host` lists in `needs`
# and requires skipped-or-success from, so a failure skips `host`, which skips
# publish and announce, which is where the GitHub Release is created.
# Detection for the execution, prevention for the publication.
#
# Usage:
#   ./scripts/verify-cargo-dist-installer.sh          # version from config
#   ./scripts/verify-cargo-dist-installer.sh 0.32.0
#
# Set INSTALLER_OUT_DIR to keep the verified scripts, so a caller can run the
# bytes this script just checked instead of downloading them again:
#   INSTALLER_OUT_DIR=/tmp/d ./scripts/verify-cargo-dist-installer.sh
#   sh /tmp/d/cargo-dist-installer.sh
#
# When bumping `cargo-dist-version`, refresh the pins with:
#   for f in cargo-dist-installer.sh cargo-dist-installer.ps1; do
#     curl -sSfL "https://github.com/axodotdev/cargo-dist/releases/download/v<NEW>/$f" \
#       | shasum -a 256 | sed "s|-|$f|"
#   done > scripts/cargo-dist-installers.sha256
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECKSUM_FILE="${REPO_ROOT}/scripts/cargo-dist-installers.sha256"
CONFIG_FILE="${REPO_ROOT}/dist-workspace.toml"
RELEASE_BASE_URL="https://github.com/axodotdev/cargo-dist/releases/download"

# The installers the generated workflow pipes into a shell: the POSIX one on
# the Linux and macOS runners, the PowerShell one on the Windows runner.
INSTALLERS=(cargo-dist-installer.sh cargo-dist-installer.ps1)

# Single source of truth for the version: the same key the generated workflow
# builds its download URL from.
if [[ $# -ge 1 ]]; then
    VERSION="$1"
else
    VERSION="$(sed -n 's/^cargo-dist-version *= *"\([^"]*\)".*/\1/p' "${CONFIG_FILE}")"
fi
if [[ -z "${VERSION}" ]]; then
    echo "error: could not determine cargo-dist-version from ${CONFIG_FILE}" >&2
    exit 1
fi

# `sha256sum` on Linux runners, `shasum -a 256` on macOS; pick whichever
# exists rather than assuming a platform.
if command -v sha256sum >/dev/null 2>&1; then
    sha256() { sha256sum "$1" | cut -d' ' -f1; }
elif command -v shasum >/dev/null 2>&1; then
    sha256() { shasum -a 256 "$1" | cut -d' ' -f1; }
else
    echo "error: neither sha256sum nor shasum is available" >&2
    exit 1
fi

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "verifying cargo-dist ${VERSION} installers against ${CHECKSUM_FILE}"
failed=0
for installer in "${INSTALLERS[@]}"; do
    expected="$(awk -v name="${installer}" '$2 == name { print $1 }' "${CHECKSUM_FILE}")"
    if [[ -z "${expected}" ]]; then
        echo "error: no pinned checksum for ${installer} in ${CHECKSUM_FILE}" >&2
        failed=1
        continue
    fi

    url="${RELEASE_BASE_URL}/v${VERSION}/${installer}"
    if ! curl --proto '=https' --tlsv1.2 -sSfL -o "${WORK_DIR}/${installer}" "${url}"; then
        echo "error: could not download ${url}" >&2
        failed=1
        continue
    fi

    actual="$(sha256 "${WORK_DIR}/${installer}")"
    if [[ "${actual}" != "${expected}" ]]; then
        echo "error: ${installer} does not match its pinned checksum" >&2
        echo "  url:      ${url}" >&2
        echo "  expected: ${expected}" >&2
        echo "  actual:   ${actual}" >&2
        echo "  Either upstream re-published the asset (bump the pin deliberately," >&2
        echo "  after reading the diff) or the release assets were tampered with." >&2
        failed=1
        continue
    fi
    echo "ok: ${installer} ${actual}"
    if [[ -n "${INSTALLER_OUT_DIR:-}" ]]; then
        mkdir -p "${INSTALLER_OUT_DIR}"
        cp "${WORK_DIR}/${installer}" "${INSTALLER_OUT_DIR}/${installer}"
    fi
done

if ((failed != 0)); then
    exit 1
fi
echo "cargo-dist installer checksums verified"
