//! Build-pipeline tests: assert the IR table generated by build.rs from the
//! vendored spec has the expected shape.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use engine::ParamType;
use otl::ops;

#[test]
fn table_contains_more_than_ten_documents_ops() {
    assert!(
        ops::OPS.len() > 10,
        "expected > 10 documents.* operations, got {}",
        ops::OPS.len()
    );
}

#[test]
fn table_contains_key_operations() {
    assert!(ops::find("documents.info").is_some());
    assert!(ops::find("documents.search").is_some());
}

#[test]
fn every_op_is_a_documents_op_with_matching_path() {
    for op in ops::OPS {
        assert!(
            op.name.starts_with("documents."),
            "unexpected op {:?}",
            op.name
        );
        assert_eq!(op.path.as_ref(), format!("/{}", op.name));
    }
}

#[test]
fn documents_info_has_string_id_param() {
    let op = ops::find("documents.info").unwrap();
    let param = op.param("id").unwrap();
    assert_eq!(param.ty, ParamType::String);
}

#[test]
fn required_params_are_marked() {
    // Upstream spec marks `id` as required for documents.update.
    let op = ops::find("documents.update").unwrap();
    let param = op.param("id").unwrap();
    assert!(param.required);
}

#[test]
fn find_returns_none_for_unknown_operation() {
    assert!(ops::find("documents.doesNotExist").is_none());
}
